ipv6: false
mode: rule
geodata-mode: true
tcp-concurrent: true
enable-process: true
geodata-loader: memconservative
inbound-tfo: false
log-level: debug
allow-lan: true
external-controller: 0.0.0.0:9090
secret: "reoreo"
bind-address: "*"
unified-delay: false
profile:
  store-selected: true
  store-fake-ip: false
  
tun:
  enable: true
  device: utun
  stack: system
  dns-hijack:
    - 0.0.0.0:1053
  auto-route: true
  auto-detect-interface: true
  mtu: 9000
  strict-route: false
  inet4-route-address:
    - 0.0.0.0/1
    - 128.0.0.0/1
  inet6-route-address:
    - '::/1'
    - '8000::/1'
  exclude-package:
    - com.mobile.legends
dns:
  enable: true
  ipv6: false
  prefer-h3: false
  listen: 0.0.0.0:1053
  use-hosts: true
  enhanced-mode: redir-host
  fake-ip-range: 198.18.188.128/25
  fake-ip-filter: ["*.local", "*.localhost"]
  nameserver:
    - 8.8.8.8
  default-nameserver:
    - 8.8.8.8

proxies:
  - name: SG-HE 1 Trojan-gm
    type: vmess
    server: cf-vod.nimo.tv
    port: 80
    uuid: e07135b0-aa78-11ef-b732-205c6d5f5d78
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: asia1.fufo.org
    network: ws
    ws-opts:
      path: /vmws
      headers:
        Host: asia1.fufo.org
    udp: true
  - name: SG-HE 2 Trojan-gm
    server: cf-vod.nimo.tv
    port: 443
    type: trojan
    password: d0a7c0c0-a3dc-11ef-90a5-1239d0255272
    tls: true
    skip-cert-verify: true
    sni: sg2-trojan.bonds.id
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: sg2-trojan.bonds.id
    udp: true
  - name: SG-HE 3 Trojan-gm
    type: trojan
    server: cf-vod.nimo.tv
    port: 443
    password: fefb64c0-aa79-11ef-8671-1239d0255272
    tls: true
    skip-cert-verify: true
    sni: sg3-trojan.bonds.id
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: sg3-trojan.bonds.id
    udp: true
  - name: t-melbi-gm
    type: vmess
    server: cf-vod.nimo.tv
    port: 80
    uuid: 67157596-4b16-5380-8061-7b65c60e1c70
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: sg3.v2vmess.site
    network: ws
    ws-opts:
      path: /vmess#DONT-FORGET-TO-SUPPORT-SSHMAX.NET-TO-KEEP-THIS-SERVER-ALIVE
      headers:
        Host: sg3.v2vmess.site
    udp: true

proxy-groups:
  - name: ♻️Trojan-SG
    type: load-balance
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 800
    lazy: false
    strategy: consistent-hashing
    disable-udp: false
    proxies:
      - SG-HE 1 Trojan-gm
      - SG-HE 2 Trojan-gm
      - SG-HE 3 Trojan-gm
      - t-melbi-gm
      
rules:
  - AND, (PROCESS-NAME,com.mobile.legends),(NOT,((DST-PORT,30101/30021/30071/30104))),DIRECT
  - MATCH,♻️Trojan-SG
