proxy-providers:
  Trojan-SG:
    type: file
    url: "https://raw.githubusercontent.com/reokadhafi/Clash-Config/main/account/trojan_sg.yaml"
    path: ./confs/config/trojan_sg.yaml
    health-check:
      enable: true
      interval: 86400
      lazy: true
      url: 'http://www.gstatic.com/generate_204'
  Vmsess-Fastssh:
    type: file
    url: "https://raw.githubusercontent.com/reokadhafi/Clash-Config/main/account/vmess_fastssh.yaml"
    path: ./confs/config/vmess_fastssh.yaml
    health-check:
      enable: true
      interval: 86400
      lazy: true
      url: 'http://www.gstatic.com/generate_204'

proxy-groups:
  - name: ✅Select
    type: select
    disable-udp: false
    proxies:
      - ♻️Trojan-SG
      - 🔁Vmess-Fastssh

  - name: ♻️Trojan-SG
    type: load-balance
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 300
    strategy: consistent-hashing
    disable-udp: false
    use:
      - Trojan-SG

  - name: 🔁Vmess-Fastssh
    type: load-balance
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 300
    strategy: consistent-hashing
    disable-udp: false
    use:
      - Vmess-Fastssh

rule-providers:
  GAME:
    type: file
    behavior: classical
    url: "https://raw.githubusercontent.com/reokadhafi/Clash-Config/main/rules/game.yaml"
    path: ./confs/config/game.yaml
    
rules:
  - RULE-SET,GAME,DIRECT 
  - MATCH,✅Select
