ipv6: false
mode: rule
geodata-mode: true
tcp-concurrent: true
enable-process: true
geodata-loader: memconservative
inbound-tfo: false
log-level: debug
allow-lan: true
external-controller: 0.0.0.0:9090
secret: "reoreo"
bind-address: "*"
unified-delay: false
profile:
  store-selected: true
  store-fake-ip: false
  
tun:
  enable: true
  device: utun
  stack: system
  dns-hijack:
    - 0.0.0.0:1053
  auto-route: true
  auto-detect-interface: true
  mtu: 9000
  strict-route: false
  inet4-route-address:
    - 0.0.0.0/1
    - 128.0.0.0/1
  inet6-route-address:
    - '::/1'
    - '8000::/1'
  exclude-package:
    - com.mobile.legends
dns:
  enable: true
  ipv6: false
  prefer-h3: false
  listen: 0.0.0.0:1053
  use-hosts: true
  enhanced-mode: redir-host
  fake-ip-range: 198.18.188.128/25
  fake-ip-filter: ["*.local", "*.localhost"]
  nameserver:
    - 8.8.8.8
  default-nameserver:
    - 8.8.8.8

proxies:
  - name: SG-HE 1 Trojan-gm
    type: trojan
    server: cf-vod.nimo.tv
    port: 443
    password: 8343ce60-a471-11ef-b832-205c6d5f5d78
    tls: true
    skip-cert-verify: true
    sni: asia1.fufo.org
    network: grpc
    grpc-opts:
      grpc-service-name: trgrpc
    udp: true
  - name: SG-HE 2 Trojan-gm
    server: cf-vod.nimo.tv
    port: 443
    type: trojan
    password: ed5226a0-a3dc-11ef-b624-1239d0255272
    tls: true
    skip-cert-verify: true
    sni: sg2-trojan.bonds.id
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: sg2-trojan.bonds.id
    udp: true
  - name: SG-HE 3 Trojan-gm
    server: cf-vod.nimo.tv
    port: 443
    type: trojan
    password: 0a05f990-9459-11ef-900e-1239d0255272
    tls: true
    skip-cert-verify: true
    sni: sg3-trojan.bonds.id
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: sg3-trojan.bonds.id
    udp: true
  - name: t-melbi-gm
    server: cf-vod.nimo.tv
    port: 443
    type: trojan
    password: 9efa6390-5e10-11ef-ad64-1239d0255272
    tls: true
    skip-cert-verify: true
    sni: sg-4.test3.net
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: sg-4.test3.net
    udp: true

proxy-groups:
  - name: ♻️Trojan-SG
    type: load-balance
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 800
    lazy: false
    strategy: consistent-hashing
    disable-udp: false
    proxies:
      - SG-HE 1 Trojan-gm
      - SG-HE 2 Trojan-gm
      - SG-HE 3 Trojan-gm
      - t-melbi-gm
      
rules:
  - AND, (PROCESS-NAME,com.mobile.legends),(NOT,((DST-PORT,30101/30021/30071/30104))),DIRECT
  - MATCH,♻️Trojan-SG
